### ISSUE TITLE
Can it run on Big Sur and M1 Macs?

### ISSUE THREAD

**Issue by StephenHaney** [steveruizok/telestrator#1]
Hey Steve, really cool app idea. I'm about to film some tutorial videos and I'd love to try it out.

When I download the release on an M1 Mac, I get this when I run it:
![image](https://user-images.githubusercontent.com/4045376/107826336-95e04b00-6d39-11eb-8de3-4d97a7393fc4.png)

I do have permissions to the file and I've tried a bunch of solutions from the internet but nothing seems to work. Any ideas?

**Comment by StephenHaney** [comment]
Aah, I ran `sudo chmod -R 755 Telestrator.app` and I'm further along, now I get the below error. I'm guessing this is an M1 thing?

![image](https://user-images.githubusercontent.com/4045376/107826819-64b44a80-6d3a-11eb-87b7-f464e7aabb12.png)

**Comment by steveruizok** [comment]
I'll look into this, thanks. I'm developing it on an M1 mac, so it certainly runs on that system. You might try building it from source until I get the rest worked out?

**Comment by StephenHaney** [comment]
Thanks, that worked. No fade / shapes in `main` yet?

For anyone with the same issue:
```
clone
yarn
yarn build
run Telestrator.app from /dist/mac
```

**Comment by junoatscroll** [comment]
I'm getting the same issue on an intel mac, bigsur, in the GH released package for versions 0.1.0 and 0.2.0

**Comment by steveruizok** [comment]
> Thanks, that worked. Very cool. No fade / shapes in main yet?

I pushed that release right around the same time as your reply, give it another look?

**Comment by steveruizok** [comment]
| I'm getting the same issue on an intel mac, bigsur, in the GH released package for versions 0.1.0 and 0.2.0

Thanks for confirming that it's not just an M1 issue, I'll chase it this weekend. 👍

**Comment by junoatscroll** [comment]
Same issue- you can see in this screenshot it's the 0.2.0 release
![image](https://user-images.githubusercontent.com/47402989/107832919-8b787e00-6d46-11eb-90b1-dcc014b32e11.png)

**Comment by steveruizok** [comment]
Just pushed a new release that should be properly signed and notarized. If you had problems before, would you please [download a copy](https://github.com/steveruizok/telestrator/releases/tag/v0.2.1) and confirm whether it works for you?

**Comment by StephenHaney** [comment]
Hey Steve, success! I downloaded `TLDraw-0.2.1.dmg` and used the installer to drag TLDraw into Applications. On first run it just reminded me it was an application downloaded from the internet, but provided an "open" button. A few seconds later it was running. 

(Note: when I download the `TLDraw-0.2.1-mac.zip` and drag the app into Applications myself, I get that same permissions error from the original post)

**Comment by steveruizok** [comment]
Excellent! I'll close this issue. 

As for the warning: I believe that will appear with anything not downloaded from the App store, so nothing unique to this app. IIRC there's an option to ignore these warnings in the OS.
