### ISSUE TITLE
Works in windows with npm?

### ISSUE THREAD

**Issue by elgransan** [steveruizok/telestrator#10]
I tried to compile and I get this error

![image](https://user-images.githubusercontent.com/9949584/114777207-cfd5c980-9d49-11eb-9dcb-c5bcfb1ca52a.png)

**Comment by steveruizok** [comment]
I'll look into this but I'm not 100% sure that the stuff we're doing with transparent / frameless windows in Electron is supported on Windows. I'll make a note to ask someone with more experience here.

**Comment by steveruizok** [comment]
Closed as supporting windows is not in scope for this project until Electron supports the required feature set. Sorry!
