### ISSUE TITLE
Overflow scrollbars

### ISSUE THREAD

**Issue by StephenHaney** [steveruizok/telestrator#3]
When drawing to the edge of the screen, I get overflow scrollbars.

These prevent the "up" event from firing, so my drawing gets locked onto the screen forever.

release: 0.2.1
macOS newest 11.2.1
m1 mac mini

![image](https://user-images.githubusercontent.com/4045376/107997820-99254200-6f98-11eb-97e6-b1011a6982e2.png)

What's more, with this OS setting, the scrollbars stay on once you mouse over the edge (whether you're drawing or not)

![image](https://user-images.githubusercontent.com/4045376/107998439-fa014a00-6f99-11eb-800b-8f73dbbbfe4b.png)

**Comment by steveruizok** [comment]
Could you check whether this is still the case? I'm pretty sure I've solved it.

**Comment by StephenHaney** [comment]
Still seeing this one. Any time I draw into the right or bottom edge of the screen I get scrollbars. Just let me know if I can provide more helpful info or videos.

**Comment by StephenHaney** [comment]
This appears to be fixed in the newest version!
