### ISSUE TITLE
Hotkeys to toggle drawing or cursor

### ISSUE THREAD

**Issue by StephenHaney** [steveruizok/telestrator#4]
My biggest feature request before I can use this while filming is a hotkey to toggle between drawing mode and my normal mouse cursor.

Right now it appears I can hit `escape` to get back to my cursor, but then I need to move back to the bottom left of my screen to reselect drawing. I need the ability to quickly toggle back and forth or it's a distracting pause in my content.

Edit: I see also there _are_ hotkeys, but they only work if the app already has focus. So, once I'm in cursor mode, there's no hotkey to get back into drawing mode, though I could be missing it.

Double edit: another data point, `alt + tabbing` back to TLDraw does **not** focus it enough for the hotkeys to work.

**Comment by steveruizok** [comment]
Good call — I'll look into global hotkeys. https://www.electronjs.org/docs/api/global-shortcut

**Comment by StephenHaney** [comment]
Yes! This appears to be solved with 0.3.0 introducing `cmd + opt + z`. Would love to be able to customize :D I'd probably set something like cmd + tilde key.
