### ISSUE TITLE
Fast strokes not always picked up in 0.3.2

### ISSUE THREAD

**Issue by StephenHaney** [steveruizok/telestrator#8]
I hit this most often when drawing the horizontal line in my `H`'s. A majority of my short horizontal strokes only get a dot at the mouseup position.

In this video, all the strokes begin and end in roughly the same place. You'll see most just end up with a dot at the end.

This seems to be the same across both pen modes.

https://user-images.githubusercontent.com/4045376/110036877-86c63a80-7cf2-11eb-8dba-b21ba3fd0eaf.mov

**Comment by StephenHaney** [comment]
On further testing, this appears to have more to do with the speed that the cursor leaves the initial mouse position. I can get the same result with long strokes, as long as I'm moving the cursor from the pointer down position quickly.

**Comment by steveruizok** [comment]
This is a weird one, I'll look into it! I tend to test more with cursive strokes so I may have just missed something with short horizontals. 🤷‍♂️

**Comment by steveruizok** [comment]
Does the same bug happen with the regular perfect freehand library? https://perfect-freehand-example.vercel.app

**Comment by StephenHaney** [comment]
It does not happen on that link. Also, in TLDraw it happens for both pen modes.

My uneducated hunch is there's some debounce logic around detecting dots? Some logic that switches between dot mode and line mode perhaps? And it's getting stuck in dot mode for these fast draws, resulting in just a dot at the end?

Here's some more testing. You'll see if I cause the bug to happen but continue holding down my mouse and move again, the full line appears from the original position.

https://user-images.githubusercontent.com/4045376/110160557-03175700-7da1-11eb-89c2-a197a73aa24f.mov

**Comment by StephenHaney** [comment]
This -might- be related, not sure. I'm not sure if the code actually differentiates between "dot mode" and "line mode" but it seems like small movements try to result in one large blob, and if you draw a certain distance it goes into a thinner line mode.

If you move very slowly, you can cause it to spaz back and forth between the two (it takes ~10+ attempts to cause this). I see this in both pen modes in TLDraw and also in Perfect Freehand Example.

https://user-images.githubusercontent.com/4045376/110161379-2098f080-7da2-11eb-8ef9-409dd0669688.mov

**Comment by steveruizok** [comment]
Yeah, seeing this too now. 🎯

**Comment by StephenHaney** [comment]
Just some stylistic feedback, I'm unsettled by it assuming dot and then going into line.

I am most commonly drawing lines, and every line starts with a dot that flashes and jumps away as I draw. Or sometimes, it starts with blank space and doesn't fill in for a second (I see this in TLDraw more, and I see flashes of big blobs more in Perfect Freehand).

In my opinion, it would feel sturdier if it assumed "line mode" and only jumped from small to large if it detects a dot.

Not sure if that's practical with the way it actually works, but maybe it's helpful feedback =) It's getting really good. 🚀

**Comment by steveruizok** [comment]
Ah, found the bug. Pushing a new release in a few minutes.

**Comment by steveruizok** [comment]
Should be fixed in [v0.3.3](https://github.com/steveruizok/telestrator/releases/tag/v0.3.3).

**Comment by StephenHaney** [comment]
Yes! Tested in v0.3.4 and I can't reproduce OP.

I'm still seeing it "assume blob" before switching to thin strokes, but it is consistent in the way it assumes and when it switches.

Nice fix  💯  Feels more stable.

**Comment by steveruizok** [comment]
Right on! I'm still working out how to get that "short stroke" behavior to feel right in perfect-freehand. "Short scribble" is even tougher!
